#############################################################
# example Makefile for linking 
# uses SoftRelTools/standard.mk
#############################################################

BINS =  BuildDAQConfig

SIMPLEBINS = $(BINS) 

#framework general 

override LOADLIBES += -lDAQConfig

############################################################
include SoftRelTools/standard.mk
include SoftRelTools/arch_spec_root.mk
